[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
moto_escrow = "6H3xC9yvLTM8YX8ruRDHbqmGySGTuQmdKSH8oW9jjhLF"

[programs.devnet]
moto_escrow = "6H3xC9yvLTM8YX8ruRDHbqmGySGTuQmdKSH8oW9jjhLF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
